# Generated by Django 5.0 on 2023-12-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='responsibilites',
            new_name='responsibilities',
        ),
    ]
